baseurl: /sfd2013

markdown:         rdiscount
pygments:         true
paginate:         4

title:            QDLUG
url:              http://qdlug.github.com/sfd2013

indexContent:     true

style:            /css/style.css
blogName:         SFD2013
blogDesc:         Software Freedom Day
favicon:          /favicon.ico
theme:            blue

copyright:        Copyright © 2011-2012 QDLUG All rights reserved.

eventdate:        2013/09/21
sitenotice:       经过各位的努力, 2013年SFD活动青岛站即将于9月21日在中国海洋大学举行.
wikiurl:          http://wiki.softwarefreedomday.org/2013/China/Qingdao/CoYouth_Club/Home
